language: php
php:
  - 5.5
  - 5.6

before_script:
  - ./scripts/bundle-devtools.sh .
  - mysql -e 'create database brightmachine_eventlog_test'
script: ./vendor/bin/phpunit --coverage-text --configuration phpunit.travis.xml
